'valores y principios',
'valores y principios',
'valores y principios',
'estado',
'estado',
'estado',
'violencia',
'defensa',
'violencia',
'defensa',
'defensa',
'valores y principios',
'valores y principios',
'violencia',
'defensa',
'violencia',
'valores y principios',
'defensa',
'defensa',
'valores y principios',
'valores y principios',
'espiritualidad',
'espiritualidad',
'espiritualidad',
'espiritualidad',
'defensa',
'valores y principios',
'valores y principios',
'valores y principios',
'valores y principios',
'valores y principios',
'defensa',
'defensa',
'defensa',
'defensa',
'valores y principios',
'violencia',
'defensa',
'defensa',
'violencia',
'espiritualidad',
'valores y principios',
'violencia',
'violencia',
'violencia',
'valores y principios',
'valores y principios',
'espiritualidad',
'defensa',
'defensa',

